### ISSUE TITLE
SP107E No longer supported

### ISSUE THREAD

**Issue by natemorven** [monty68/uniled#65]
## Version of the custom_component

2.2.5

## Configuration
My configuration for Home Assistant is mostly default, the only change being that I'm connecting /run/dbus between my host machine (Unraid 6.12.8) and the HA container in read-only mode.

## Describe the bug
Uniled will no longer connect to SP107E. It previously worked fine, I last used it around November-December. I'm running Home Assistant's docker container, core version 2024.2.4, frontend version 20240207.1. 

## Debug log
```text
2024-02-28 11:26:25.489 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Checking support for: '35:53:1A:05:98:AD' (SP107E)... AdvertisementData(local_name='SP107E', manufacturer_data={21301: b'\x1a\x05\x98\xad'}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-92)
2024-02-28 11:26:25.490 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Device '35:53:1A:05:98:AD' (SP107E) not supported!
```

**Comment by natemorven** [comment]
I've narrowed down a way to temporarily fix the issue for my device.

The issue seems to arise because of non-passing logic in the _match_ble_device_ method within the _UniledBleModel_ class.

Two changes I made:
1. In led_chord.py, I changed the _ble_manufacturer_id_ variable (line 124) to **21301** instead of **0**.
2. At the bottom of that same file, line 504, I changed the data variable from **b"\x00\x00"** to **[b"\x00\x00", b"\x1a\x05\x98\xad"]**. I borrowed this idea from #53.

Once I made those changes, my SP107E connected instantly. I'm not sure if the second modification actually affected anything, but the first modification definitely did.

Note: That 21301 number came from the _manufacturer_data_ shown in the _AdvertisementData_ in the debug log, aka "**mid**" in the code. Similarly, the b"\x1a\..." value also came from _AdvertisementData_ in the debug log.

**Comment by monty68** [comment]
Thanks, I have a more generic fix, which I will include in the next available update

**Comment by natemorven** [comment]
Many thanks!

**Comment by MNeubauer72** [comment]
> Thanks, I have a more generic fix, which I will include in the next available update

When do you plan to release the new version? I'm having a problem with these SP107Es, which used to work without a problem, but now HA can't connect to them.

**Comment by MNeubauer72** [comment]
This workaround doesn't work for me. SP107E was working beautifully, until here suddenly stopped - it can not be configured, nothing works. I don't know exactly at what point, but I suspect at the Home Assistant update. I have an image from before the update and there it works fine. SP621E works fine both before and after the update.

**Comment by MNeubauer72** [comment]
Hello everyone.
Good news - my SP107E started working properly without any interference with HA configuration or other things. Silly thing, I ran into it by accident. I did a small move of the hardware to another room and the controller suddenly came to life, but started having problems with other bluetooth devices. After trying to disable all bluetooth devices except for a few selected ones these worked fine. When turning on more devices, a random problem began to appear, but the SP107E continued to work properly. I bought a second bluetooth dongle and everything returned to normal, everything works properly. So if you have a problem with SP107E then count how many bluetooth devices you have and how many your bt dongle can handle. In my case the problem was too many BT devices in relation to the BT card's capabilities, which supported up to 7 connections.
That's what I think, although on the other hand it may have been the change in BT card location that caused the problems with accessing other devices. In any case, SP107E works wonderfully :)
